const links = {
    business: [
        "Finance",
        "Economy",
        "Stocks",
        "Investment",
        "Startups",
        "Markets",
        "Entrepreneurship",
        "Banking",
        "Corporate",
        "Small Business",
        "Trade",
        "Technology",
        "Retail",
        "Real Estate",
        "Manufacturing",
        "Leadership",
        "Innovation",
        "Global Business",
        "Management",
        "Sustainability"
    ],
    entertainment: [
        "Movies",
        "Music",
        "Television",
        "Celebrity News",
        "Gaming",
        "Sports",
        "Concerts",
        "Theater",
        "Art",
        "Books",
        "Fashion",
        "Comedy",
        "Pop Culture",
        "Dance",
        "Streaming",
        "Awards",
        "Events",
        "Travel",
        "Food & Dining",
        "Photography",
        "Hobbies",
        "Radio",
        "Amusement Parks",
        "Comics",
        "Magazines"
    ],
    health: [
        "Fitness",
        "Nutrition",
        "Disease Prevention",
        "Mental Health",
        "Medical Research",
        "Diet",
        "Exercise",
        "Wellness",
        "Healthcare",
        "Weight Loss",
        "Healthy Living",
        "Hospitals",
        "Medical Breakthroughs",
        "Pharmaceuticals",
        "Alternative Medicine",
        "Dental Care",
        "Public Health",
        "Health Policy",
        "Pregnancy",
        "Child Health",
        "Aging",
        "Cancer",
        "Heart Health",
        "Allergies",
        "Infectious Diseases",
        "Health Technology",
        "Vaccines",
        "Pain Management",
        "Health Education"
    ],
    science: [
        "Physics",
        "Biology",
        "Chemistry",
        "Astronomy",
        "Environmental Science",
        "Earth Sciences",
        "Medical Science",
        "Space Exploration",
        "Genetics",
        "Robotics",
        "Artificial Intelligence",
        "Climate Change",
        "Nanotechnology",
        "Neuroscience",
        "Ecology",
        "Geology",
        "Paleontology",
        "Mathematics",
        "Quantum Mechanics",
        "Biotechnology",
        "Energy Science",
        "Materials Science",
        "Computer Science",
        "Psychology",
        "Astrophysics",
        "Biomedical Research",
        "Oceanography",
        "Meteorology"
    ],
    sports: [
        "Football",
        "Basketball",
        "Soccer",
        "Baseball",
        "Tennis",
        "Golf",
        "Hockey",
        "Cricket",
        "Rugby",
        "Olympics",
        "Athletics",
        "Martial Arts",
        "Motorsports",
        "Extreme Sports",
        "Wrestling",
        "Boxing",
        "Cycling",
        "Equestrian",
        "Water Sports",
        "Esports"
    ],
    technology: [
        "Artificial Intelligence",
        "Machine Learning",
        "Cybersecurity",
        "Blockchain",
        "Internet of Things (IoT)",
        "Big Data",
        "Cloud Computing",
        "Robotics",
        "Virtual Reality",
        "Augmented Reality",
        "Gadgets",
        "Smartphones",
        "Software Development",
        "Hardware",
        "Data Science",
        "Tech Startups",
        "Digital Marketing",
        "Social Media",
        "E-commerce",
        "Biotechnology",
        "Autonomous Vehicles",
        "Space Technology",
        "Wireless Technology",
        "3D Printing",
        "Green Technology",
        "Tech Policy",
        "Tech Industry",
        "Science Fiction",
        "Innovation",
        "Tech Reviews"
    ]
};

export default links








